import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-adoption-list-itme',
  templateUrl: './adoption-list-itme.component.html',
  styleUrls: ['./adoption-list-itme.component.css']
})
export class AdoptionListItmeComponent implements OnInit {
  cit:any;
  pla=true ;
  choose:any;
  provence:any;
  constructor() { }
     data:any;
  cindex:any;
  ngOnInit() {
    this.data=this.pet[0].pett;
    this.cit=this.place[0].city;
    this.provence =this.place [0];
    this.choose='全国';
    scrollTo(0,0);
  }
 pet = [
  {
    nav: '其他',
    pett: [
      {
        'id':1,
        'uname':'张三dog3',
        'uimg':'../../../../assets/images/dog.png',
        'fristname':'日本',
        'img':'../../../../assets/images/adoption/adoption1.jpg',
        'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
        'date':'2017-4-5',
        'name':'shabi',
        'Ename':'sha',
        'form':'柯基',
        'special':'腿短',
        'commentcount':'1232',
        'browse':300,
        'isCollect':true
      },
      {
        'id':1,
        'uname':'张三dog3',
        'uimg':'../../../../assets/images/dog.png',
        'fristname':'日本',
        'img':'../../../../assets/images/adoption/adoption2.jpg',
        'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
        'date':'2017-4-5',
        'name':'shabi',
        'Ename':'sha',
        'form':'柯基',
        'special':'腿短',
        'commentcount':'1232',
        'browse':300,
        'isCollect':true
      },
      {
        'id':1,
        'uname':'张三dog3',
        'uimg':'../../../../assets/images/dog.png',
        'fristname':'日本',
        'img':'../../../../assets/images/adoption/adoption3.jpg',
        'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
        'date':'2017-4-5',
        'name':'shabi',
        'Ename':'sha',
        'form':'柯基',
        'special':'腿短',
        'commentcount':'1232',
        'browse':300,
        'isCollect':true
      },
      {
        'id':1,
        'uname':'张三dog3',
        'uimg':'../../../../assets/images/dog.png',
        'fristname':'日本',
        'img':'../../../../assets/images/adoption/adoption4.jpg',
        'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
        'date':'2017-4-5',
        'name':'shabi',
        'Ename':'sha',
        'form':'柯基',
        'special':'腿短',
        'commentcount':'1232',
        'browse':300,
        'isCollect':true
      },
      {
        'id':1,
        'uname':'张三dog3',
        'uimg':'../../../../assets/images/dog.png',
        'fristname':'日本',
        'img':'../../../../assets/images/adoption/adoption5.jpg',
        'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
        'date':'2017-4-5',
        'name':'shabi',
        'Ename':'sha',
        'form':'柯基',
        'special':'腿短',
        'commentcount':'1232',
        'browse':300,
        'isCollect':true
      },
      {
        'id':1,
        'uname':'张三dog3',
        'uimg':'../../../../assets/images/dog.png',
        'fristname':'日本',
        'img':'../../../../assets/images/adoption/adoption6.jpg',
        'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
        'date':'2017-4-5',
        'name':'shabi',
        'Ename':'sha',
        'form':'柯基',
        'special':'腿短',
        'commentcount':'1232',
        'browse':300,
        'isCollect':true
      },
      {
        'id':1,
        'uname':'张三dog3',
        'uimg':'../../../../assets/images/dog.png',
        'fristname':'日本',
        'img':'../../../../assets/images/adoption/adoption7.jpg',
        'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
        'date':'2017-4-5',
        'name':'shabi',
        'Ename':'sha',
        'form':'柯基',
        'special':'腿短',
        'commentcount':'1232',
        'browse':300,
        'isCollect':true
      },
      {
        'id':1,
        'uname':'张三dog3',
        'uimg':'../../../../assets/images/dog.png',
        'fristname':'日本',
        'img':'../../../../assets/images/adoption/adoption8.jpg',
        'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
        'date':'2017-4-5',
        'name':'shabi',
        'Ename':'sha',
        'form':'柯基',
        'special':'腿短',
        'commentcount':'1232',
        'browse':300,
        'isCollect':true
      },
      {
        'id':1,
        'uname':'张三dog3',
        'uimg':'../../../../assets/images/dog.png',
        'fristname':'日本',
        'img':'../../../../assets/images/adoption/adoption4.jpg',
        'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
        'date':'2017-4-5',
        'name':'shabi',
        'Ename':'sha',
        'form':'柯基',
        'special':'腿短',
        'commentcount':'1232',
        'browse':300,
        'isCollect':true
      },
    ],
  },


  {
    nav: '喵星人 ',
    pett: [
      {
        'id':1,
        'uname':'张三dog3',
        'uimg':'../../../../assets/images/dog.png',
        'fristname':'日本',
        'img':'../../../../assets/images/adoption/adoption1.jpg',
        'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
        'date':'2017-4-5',
        'name':'shabi',
        'Ename':'sha',
        'form':'柯基',
        'special':'腿短',
        'commentcount':'1232',
        'browse':300,
        'isCollect':true
      },
      {
        'id':1,
        'uname':'张三dog3',
        'uimg':'../../../../assets/images/dog.png',
        'fristname':'日本',
        'img':'../../../../assets/images/adoption/adoption2.jpg',
        'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
        'date':'2017-4-5',
        'name':'shabi',
        'Ename':'sha',
        'form':'柯基',
        'special':'腿短',
        'commentcount':'1232',
        'browse':300,
        'isCollect':true
      },
      {
        'id':1,
        'uname':'张三dog3',
        'uimg':'../../../../assets/images/dog.png',
        'fristname':'日本',
        'img':'../../../../assets/images/adoption/adoption3.jpg',
        'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
        'date':'2017-4-5',
        'name':'shabi',
        'Ename':'sha',
        'form':'柯基',
        'special':'腿短',
        'commentcount':'1232',
        'browse':300,
        'isCollect':true
      },
      {
        'id':1,
        'uname':'张三dog3',
        'uimg':'../../../../assets/images/dog.png',
        'fristname':'日本',
        'img':'../../../../assets/images/adoption/adoption4.jpg',
        'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
        'date':'2017-4-5',
        'name':'shabi',
        'Ename':'sha',
        'form':'柯基',
        'special':'腿短',
        'commentcount':'1232',
        'browse':300,
        'isCollect':true
      },
      {
        'id':1,
        'uname':'张三dog3',
        'uimg':'../../../../assets/images/dog.png',
        'fristname':'日本',
        'img':'../../../../assets/images/adoption/adoption5.jpg',
        'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
        'date':'2017-4-5',
        'name':'shabi',
        'Ename':'sha',
        'form':'柯基',
        'special':'腿短',
        'commentcount':'1232',
        'browse':300,
        'isCollect':true
      },
      {
        'id':1,
        'uname':'张三dog3',
        'uimg':'../../../../assets/images/dog.png',
        'fristname':'日本',
        'img':'../../../../assets/images/adoption/adoption6.jpg',
        'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
        'date':'2017-4-5',
        'name':'shabi',
        'Ename':'sha',
        'form':'柯基',
        'special':'腿短',
        'commentcount':'1232',
        'browse':300,
        'isCollect':true
      },
      {
        'id':1,
        'uname':'张三dog3',
        'uimg':'../../../../assets/images/dog.png',
        'fristname':'日本',
        'img':'../../../../assets/images/adoption/adoption7.jpg',
        'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
        'date':'2017-4-5',
        'name':'shabi',
        'Ename':'sha',
        'form':'柯基',
        'special':'腿短',
        'commentcount':'1232',
        'browse':300,
        'isCollect':true
      },
      {
        'id':1,
        'uname':'张三dog3',
        'uimg':'../../../../assets/images/dog.png',
        'fristname':'日本',
        'img':'../../../../assets/images/adoption/adoption8.jpg',
        'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
        'date':'2017-4-5',
        'name':'shabi',
        'Ename':'sha',
        'form':'柯基',
        'special':'腿短',
        'commentcount':'1232',
        'browse':300,
        'isCollect':true
      },
      {
        'id':1,
        'uname':'张三dog3',
        'uimg':'../../../../assets/images/dog.png',
        'fristname':'日本',
        'img':'../../../../assets/images/adoption/adoption4.jpg',
        'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
        'date':'2017-4-5',
        'name':'shabi',
        'Ename':'sha',
        'form':'柯基',
        'special':'腿短',
        'commentcount':'1232',
        'browse':300,
        'isCollect':true
      },
    ],
  },
  {
    nav : '汪星人',
    pett:[
      {
        'id':1,
        'uname':'张三dog1',

        'uimg':'../../../../assets/images/dog.png',
        'fristname':'日本',
        'img':'../../../../assets/images/adoption/ttt.jpg',
        'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
        'date':'2017-4-5',
        'name':'shabi',
        'Ename':'sha',
        'form':'柯基',
        'special':'腿短',
        'commentcount':'1232',
        'browse':300,
        'isCollect':true

      },
      {
        'id':1,
        'uname':'张三dog2',

        'uimg':'../../../../assets/images/dog.png',
        'fristname':'日本',
        'img':'../../../../assets/images/adoption/rrr.jpg',
        'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
        'date':'2017-4-5',
        'name':'shabi',
        'Ename':'sha',
        'form':'柯基',
        'special':'腿短',
        'commentcount':'12',
        'browse':300,
        'isCollect':true
      },
      {
        'id':1,
        'uname':'张三dog3',
        'uimg':'../../../../assets/images/dog.png',
        'fristname':'日本',
        'img':'../../../../assets/images/dog1.png',
        'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
        'date':'2017-4-5',
        'name':'shabi',
        'Ename':'sha',
        'form':'柯基',
        'special':'腿短',
        'commentcount':'1232',
        'browse':300,
        'isCollect':true
      },
      {
        'id':1,
        'uname':'张三dog3',
        'uimg':'../../../../assets/images/dog.png',
        'fristname':'日本',
        'img':'../../../../assets/images/adoption/adoption1.jpg',
        'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
        'date':'2017-4-5',
        'name':'shabi',
        'Ename':'sha',
        'form':'柯基',
        'special':'腿短',
        'commentcount':'1232',
        'browse':300,
        'isCollect':true
      },
      {
        'id':1,
        'uname':'张三dog3',
        'uimg':'../../../../assets/images/dog.png',
        'fristname':'日本',
        'img':'../../../../assets/images/adoption/adoption2.jpg',
        'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
        'date':'2017-4-5',
        'name':'shabi',
        'Ename':'sha',
        'form':'柯基',
        'special':'腿短',
        'commentcount':'1232',
        'browse':300,
        'isCollect':true
      },
      {
        'id':1,
        'uname':'张三dog3',
        'uimg':'../../../../assets/images/dog.png',
        'fristname':'日本',
        'img':'../../../../assets/images/adoption/adoption3.jpg',
        'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
        'date':'2017-4-5',
        'name':'shabi',
        'Ename':'sha',
        'form':'柯基',
        'special':'腿短',
        'commentcount':'1232',
        'browse':300,
        'isCollect':true
      },
      {
        'id':1,
        'uname':'张三dog3',
        'uimg':'../../../../assets/images/dog.png',
        'fristname':'日本',
        'img':'../../../../assets/images/adoption/adoption4.jpg',
        'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
        'date':'2017-4-5',
        'name':'shabi',
        'Ename':'sha',
        'form':'柯基',
        'special':'腿短',
        'commentcount':'1232',
        'browse':300,
        'isCollect':true
      },
      {
        'id':1,
        'uname':'张三dog3',
        'uimg':'../../../../assets/images/dog.png',
        'fristname':'日本',
        'img':'../../../../assets/images/adoption/adoption5.jpg',
        'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
        'date':'2017-4-5',
        'name':'shabi',
        'Ename':'sha',
        'form':'柯基',
        'special':'腿短',
        'commentcount':'1232',
        'browse':300,
        'isCollect':true
      },
      {
        'id':1,
        'uname':'张三dog3',
        'uimg':'../../../../assets/images/dog.png',
        'fristname':'日本',
        'img':'../../../../assets/images/adoption/adoption6.jpg',
        'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
        'date':'2017-4-5',
        'name':'shabi',
        'Ename':'sha',
        'form':'柯基',
        'special':'腿短',
        'commentcount':'1232',
        'browse':300,
        'isCollect':true
      },
      {
        'id':1,
        'uname':'张三dog3',
        'uimg':'../../../../assets/images/dog.png',
        'fristname':'日本',
        'img':'../../../../assets/images/adoption/adoption7.jpg',
        'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
        'date':'2017-4-5',
        'name':'shabi',
        'Ename':'sha',
        'form':'柯基',
        'special':'腿短',
        'commentcount':'1232',
        'browse':300,
        'isCollect':true
      },
      {
        'id':1,
        'uname':'张三dog3',
        'uimg':'../../../../assets/images/dog.png',
        'fristname':'日本',
        'img':'../../../../assets/images/adoption/adoption8.jpg',
        'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
        'date':'2017-4-5',
        'name':'shabi',
        'Ename':'sha',
        'form':'柯基',
        'special':'腿短',
        'commentcount':'1232',
        'browse':300,
        'isCollect':true
      },
      {
        'id':1,
        'uname':'张三dog3',
        'uimg':'../../../../assets/images/dog.png',
        'fristname':'日本',
        'img':'../../../../assets/images/adoption/adoption4.jpg',
        'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
        'date':'2017-4-5',
        'name':'shabi',
        'Ename':'sha',
        'form':'柯基',
        'special':'腿短',
        'commentcount':'1232',
        'browse':300,
        'isCollect':true
      },










    ],
  },



]
  place=[
    {
      provence:'四川',
      city:['宜宾市','广安市','达州市','雅安市','巴中市','资阳市']
    },
    {
      provence:'四川1',
      city:['宜宾市2','广安市2','达州市2','雅安市2','巴中市2','资阳市2']
    },
    {
      provence:'四川2',
      city:['宜宾市2','广安市2','达州市2','雅安市2','巴中市2','资阳市2']
    }
  ];

  exchange(i:any){
    this.data[i].isCollect=!this.data[i].isCollect;
  }

  showaa(i:any){
    this.data=this.pet[i].pett;
    this.cindex=i;

  }
//省
pro(i:any){
  console.log(i);
  this.cit =this.place[i].city;
}
  //全国显示
  placee(){
    this.pla=!this.pla;
  }

  citye(j){
    console.log(j);
    this.choose=this.cit[j]
    this.pla=!this.pla;
  }

}
