import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-adoption-list-itme',
  templateUrl: './adoption-list-itme.component.html',
  styleUrls: ['./adoption-list-itme.component.css']
})
export class AdoptionListItmeComponent implements OnInit {

  showdog(){
    this.data=this.dog;
  }
  showcat(){
    this.data=this.cat;

  }
  showfish(){
    this.data=this.fish;
  }
  showbird(){
    this.data=this.bird;
  }
  showother(){
    this.data=this.other;
  }
  constructor() { }
     data:any;
  ngOnInit() {
    this.data=this.dog;
  }

  dog=[
    {
      'id':1,
      'uname':'张三dog1',
      'width':'265',
      'height':'200',
      'uimg':'../../../../assets/images/dog.png',
      'fristname':'日本',
      'img':'../../../../assets/images/dog1.png',
      'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
      'date':'2017-4-5',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短',
      'commentcount':'1232',
      'browse':300

    },
    {
      'id':1,
      'uname':'张三dog2',
      'width':'265',
      'height':'150',
      'uimg':'../../../../assets/images/dog.png',
      'fristname':'日本',
      'img':'../../../../assets/images/dog1.png',
      'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
      'date':'2017-4-5',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':1,
      'uname':'张三dog3',
      'width':'265',
      'height':'240',
      'uimg':'../../../../assets/images/dog.png',
      'fristname':'日本',
      'img':'../../../../assets/images/dog1.png',
      'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
      'date':'2017-4-5',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },

    {
      'id':1,
      'uname':'张三dog4',
      'width':'265',
      'height':'220',
      'uimg':'../../../../assets/images/dog.png',
      'fristname':'日本',
      'img':'../../../../assets/images/dog1.png',
      'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
      'date':'2017-4-5',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':1,
      'uname':'张三dog5',
      'width':'265',
      'height':'230',
      'uimg':'../../../../assets/images/dog.png',
      'fristname':'日本',
      'img':'../../../../assets/images/dog1.png',
      'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
      'date':'2017-4-5',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':1,
      'uname':'张三dog6',
      'width':'265',
      'height':'210',
      'uimg':'../../../../assets/images/dog.png',
      'fristname':'日本',
      'img':'../../../../assets/images/dog1.png',
      'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
      'date':'2017-4-5',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':1,
      'uname':'张三dog1',
      'width':'265',
      'height':'200',
      'uimg':'../../../../assets/images/dog.png',
      'fristname':'日本',
      'img':'../../../../assets/images/dog1.png',
      'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
      'date':'2017-4-5',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':1,
      'uname':'张三dog2',
      'width':'265',
      'height':'150',
      'uimg':'../../../../assets/images/dog.png',
      'fristname':'日本',
      'img':'../../../../assets/images/dog1.png',
      'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
      'date':'2017-4-5',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':1,
      'uname':'张三dog3',
      'width':'265',
      'height':'240',
      'uimg':'../../../../assets/images/dog.png',
      'fristname':'日本',
      'img':'../../../../assets/images/dog1.png',
      'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
      'date':'2017-4-5',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },

    {
      'id':1,
      'uname':'张三dog4',
      'width':'265',
      'height':'220',
      'uimg':'../../../../assets/images/dog.png',
      'fristname':'日本',
      'img':'../../../../assets/images/dog1.png',
      'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
      'date':'2017-4-5',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':1,
      'uname':'张三dog5',
      'width':'265',
      'height':'230',
      'uimg':'../../../../assets/images/dog.png',
      'fristname':'日本',
      'img':'../../../../assets/images/dog1.png',
      'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
      'date':'2017-4-5',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':1,
      'uname':'张三dog6',
      'width':'265',
      'height':'210',
      'uimg':'../../../../assets/images/dog.png',
      'fristname':'日本',
      'img':'../../../../assets/images/dog1.png',
      'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
      'date':'2017-4-5',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },

    {
      'id':1,
      'uname':'张三dog1',
      'width':'265',
      'height':'200',
      'uimg':'../../../../assets/images/dog.png',
      'fristname':'日本',
      'img':'../../../../assets/images/dog1.png',
      'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
      'date':'2017-4-5',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':1,
      'uname':'张三dog2',
      'width':'265',
      'height':'150',
      'uimg':'../../../../assets/images/dog.png',
      'fristname':'日本',
      'img':'../../../../assets/images/dog1.png',
      'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
      'date':'2017-4-5',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':1,
      'uname':'张三dog3',
      'width':'265',
      'height':'240',
      'uimg':'../../../../assets/images/dog.png',
      'fristname':'日本',
      'img':'../../../../assets/images/dog1.png',
      'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
      'date':'2017-4-5',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },

    {
      'id':1,
      'uname':'张三dog4',
      'width':'265',
      'height':'220',
      'uimg':'../../../../assets/images/dog.png',
      'fristname':'日本',
      'img':'../../../../assets/images/dog1.png',
      'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
      'date':'2017-4-5',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':1,
      'uname':'张三dog5',
      'width':'265',
      'height':'230',
      'uimg':'../../../../assets/images/dog.png',
      'fristname':'日本',
      'img':'../../../../assets/images/dog1.png',
      'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
      'date':'2017-4-5',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':1,
      'uname':'张三dog6',
      'width':'265',
      'height':'210',
      'uimg':'../../../../assets/images/dog.png',
      'fristname':'日本',
      'img':'../../../../assets/images/dog1.png',
      'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
      'date':'2017-4-5',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':1,
      'uname':'张三dog1',
      'width':'265',
      'height':'200',
      'uimg':'../../../../assets/images/dog.png',
      'fristname':'日本',
      'img':'../../../../assets/images/dog1.png',
      'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
      'date':'2017-4-5',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':1,
      'uname':'张三dog2',
      'width':'265',
      'height':'150',
      'uimg':'../../../../assets/images/dog.png',
      'fristname':'日本',
      'img':'../../../../assets/images/dog1.png',
      'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
      'date':'2017-4-5',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':1,
      'uname':'张三dog3',
      'width':'265',
      'height':'240',
      'uimg':'../../../../assets/images/dog.png',
      'fristname':'日本',
      'img':'../../../../assets/images/dog1.png',
      'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
      'date':'2017-4-5',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },

    {
      'id':1,
      'uname':'张三dog4',
      'width':'265',
      'height':'220',
      'uimg':'../../../../assets/images/dog.png',
      'fristname':'日本',
      'img':'../../../../assets/images/dog1.png',
      'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
      'date':'2017-4-5',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':1,
      'uname':'张三dog5',
      'width':'265',
      'height':'230',
      'uimg':'../../../../assets/images/dog.png',
      'fristname':'日本',
      'img':'../../../../assets/images/dog1.png',
      'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
      'date':'2017-4-5',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':1,
      'uname':'张三dog6',
      'width':'265',
      'height':'210',
      'uimg':'../../../../assets/images/dog.png',
      'fristname':'日本',
      'img':'../../../../assets/images/dog1.png',
      'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
      'date':'2017-4-5',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },



  ];
  cat=[
    {
      'id':1,
      'uname':'张三cat',
      'uimg':'../../../../assets/images/dog.png',
      'fristname':'日本',
      'img':'../../../../assets/images/dog1.png',
      'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
      'date':'2017-4-5',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':2,
      'img':'../../../../assets/images/dog1.png',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':3,
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短',
      'img':'../../../../assets/images/dog1.png'
    }, {
      'id':4,
      'img':'../../../../assets/images/dog1.png',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':5,
      'img':'../../../../assets/images/dog1.png',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':6,
      'img':'../../../../assets/images/dog1.png',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':7,
      'img':'../../../../assets/images/dog1.png',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':8,
      'img':'../../../../assets/images/dog1.png',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    }
  ];
  bird=[
    {
      'id':1,
      'uname':'张三bird',
      'uimg':'../../../../assets/images/dog1.png',
      'fristname':'日本',
      'img':'../../../../assets/images/dog1.png',
      'introduce':'健康没毛病,第一针疫苗打完，洗过澡了，指甲剪了，希望你好好对他负责',
      'date':'2017-4-5',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':2,
      'img':'../../../../assets/images/dog1.png',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'wonfdk腿短'
    },
    {
      'id':3,
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'hfdj腿短',
      'img':'../../../../assets/images/dog1.png'
    }, {
      'id':4,
      'img':'../../../../assets/images/dog1.png',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'hj腿短'
    },
    {
      'id':5,
      'img':'../../../../assets/images/dog1.png',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':6,
      'img':'../../../../assets/images/dog1.png',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':7,
      'img':'../../../../assets/images/dog1.png',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':8,
      'img':'../../../../assets/images/dog1.png',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    }
  ];
  fish=[
    {
      'id':1,
      'fristname':'1111111111111日本',
      'img':'../../../../assets/images/dog1.png',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'fish腿短1111'
    },
    {
      'id':2,
      'img':'../../../../assets/images/dog1.png',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':3,
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短',
      'img':'../../../../assets/images/dog1.png'
    }, {
      'id':4,
      'img':'../../../../assets/images/dog1.png',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':5,
      'img':'../../../../assets/images/dog1.png',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':6,
      'img':'../../../../assets/images/dog1.png',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':7,
      'img':'../../../../assets/images/dog1.png',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':8,
      'img':'../../../../assets/images/dog1.png',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    }
  ];
  other=[
    {
      'id':1,
      'fristname':'1111111111111日本',
      'img':'../../../../assets/images/dog1.png',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'other腿短1111'
    },
    {
      'id':2,
      'img':'../../../../assets/images/dog1.png',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':3,
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短',
      'img':'../../../../assets/images/dog1.png'
    }, {
      'id':4,
      'img':'../../../../assets/images/dog1.png',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':5,
      'img':'../../../../assets/images/dog1.png',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':6,
      'img':'../../../../assets/images/dog1.png',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':7,
      'img':'../../../../assets/images/dog1.png',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    },
    {
      'id':8,
      'img':'../../../../assets/images/dog1.png',
      'name':'shabi',
      'Ename':'sha',
      'form':'柯基',
      'special':'腿短'
    }
  ];

}
